//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsTis
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS", ConfigurationName="wsTis.MES_TISSoap")]
    public interface MES_TISSoap
    {
        
        // CODEGEN: Generating message contract since element name CustomerName from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/OKToTest", ReplyAction="*")]
        wsTis.OKToTestResponse OKToTest(wsTis.OKToTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/OKToTest", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.OKToTestResponse> OKToTestAsync(wsTis.OKToTestRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerName from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/OKToTestLinkMaterial", ReplyAction="*")]
        wsTis.OKToTestLinkMaterialResponse OKToTestLinkMaterial(wsTis.OKToTestLinkMaterialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/OKToTestLinkMaterial", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.OKToTestLinkMaterialResponse> OKToTestLinkMaterialAsync(wsTis.OKToTestLinkMaterialRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerName from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetPanelSerializeResult", ReplyAction="*")]
        wsTis.GetPanelSerializeResultResponse GetPanelSerializeResult(wsTis.GetPanelSerializeResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetPanelSerializeResult", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.GetPanelSerializeResultResponse> GetPanelSerializeResultAsync(wsTis.GetPanelSerializeResultRequest request);
        
        // CODEGEN: Generating message contract since element name SerialNumber from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/LookupCustAssy", ReplyAction="*")]
        wsTis.LookupCustAssyResponse LookupCustAssy(wsTis.LookupCustAssyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/LookupCustAssy", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.LookupCustAssyResponse> LookupCustAssyAsync(wsTis.LookupCustAssyRequest request);
        
        // CODEGEN: Generating message contract since element name SerialNumber from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetCurrentRouteStep", ReplyAction="*")]
        wsTis.GetCurrentRouteStepResponse GetCurrentRouteStep(wsTis.GetCurrentRouteStepRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetCurrentRouteStep", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.GetCurrentRouteStepResponse> GetCurrentRouteStepAsync(wsTis.GetCurrentRouteStepRequest request);
        
        // CODEGEN: Generating message contract since element name GetTestDataFormatsResult from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetTestDataFormats", ReplyAction="*")]
        wsTis.GetTestDataFormatsResponse GetTestDataFormats(wsTis.GetTestDataFormatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetTestDataFormats", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.GetTestDataFormatsResponse> GetTestDataFormatsAsync(wsTis.GetTestDataFormatsRequest request);
        
        // CODEGEN: Generating message contract since element name TestData from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/ProcessTestData", ReplyAction="*")]
        wsTis.ProcessTestDataResponse ProcessTestData(wsTis.ProcessTestDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/ProcessTestData", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.ProcessTestDataResponse> ProcessTestDataAsync(wsTis.ProcessTestDataRequest request);
        
        // CODEGEN: Generating message contract since element name SerialNumber from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetTestHistory", ReplyAction="*")]
        wsTis.GetTestHistoryResponse GetTestHistory(wsTis.GetTestHistoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetTestHistory", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.GetTestHistoryResponse> GetTestHistoryAsync(wsTis.GetTestHistoryRequest request);
        
        // CODEGEN: Generating message contract since element name SerialNumber from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetLastTestResult", ReplyAction="*")]
        wsTis.GetLastTestResultResponse GetLastTestResult(wsTis.GetLastTestResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetLastTestResult", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.GetLastTestResultResponse> GetLastTestResultAsync(wsTis.GetLastTestResultRequest request);
        
        // CODEGEN: Generating message contract since element name GetVersionResult from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetVersion", ReplyAction="*")]
        wsTis.GetVersionResponse GetVersion(wsTis.GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/GetVersion", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.GetVersionResponse> GetVersionAsync(wsTis.GetVersionRequest request);
        
        // CODEGEN: Generating message contract since element name CustomerName from namespace http://jabil.com/GMS/MES_TIS is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/OkToTest_Breakout", ReplyAction="*")]
        wsTis.OkToTest_BreakoutResponse OkToTest_Breakout(wsTis.OkToTest_BreakoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jabil.com/GMS/MES_TIS/OkToTest_Breakout", ReplyAction="*")]
        System.Threading.Tasks.Task<wsTis.OkToTest_BreakoutResponse> OkToTest_BreakoutAsync(wsTis.OkToTest_BreakoutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OKToTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OKToTest", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.OKToTestRequestBody Body;
        
        public OKToTestRequest()
        {
        }
        
        public OKToTestRequest(wsTis.OKToTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class OKToTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SerialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AssemblyNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TesterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProcessStep;
        
        public OKToTestRequestBody()
        {
        }
        
        public OKToTestRequestBody(string CustomerName, string Division, string SerialNumber, string AssemblyNumber, string TesterName, string ProcessStep)
        {
            this.CustomerName = CustomerName;
            this.Division = Division;
            this.SerialNumber = SerialNumber;
            this.AssemblyNumber = AssemblyNumber;
            this.TesterName = TesterName;
            this.ProcessStep = ProcessStep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OKToTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OKToTestResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.OKToTestResponseBody Body;
        
        public OKToTestResponse()
        {
        }
        
        public OKToTestResponse(wsTis.OKToTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class OKToTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OKToTestResult;
        
        public OKToTestResponseBody()
        {
        }
        
        public OKToTestResponseBody(string OKToTestResult)
        {
            this.OKToTestResult = OKToTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OKToTestLinkMaterialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OKToTestLinkMaterial", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.OKToTestLinkMaterialRequestBody Body;
        
        public OKToTestLinkMaterialRequest()
        {
        }
        
        public OKToTestLinkMaterialRequest(wsTis.OKToTestLinkMaterialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class OKToTestLinkMaterialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LinkMaterialSerialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AssemblyNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TesterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProcessStep;
        
        public OKToTestLinkMaterialRequestBody()
        {
        }
        
        public OKToTestLinkMaterialRequestBody(string CustomerName, string Division, string LinkMaterialSerialNumber, string AssemblyNumber, string TesterName, string ProcessStep)
        {
            this.CustomerName = CustomerName;
            this.Division = Division;
            this.LinkMaterialSerialNumber = LinkMaterialSerialNumber;
            this.AssemblyNumber = AssemblyNumber;
            this.TesterName = TesterName;
            this.ProcessStep = ProcessStep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OKToTestLinkMaterialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OKToTestLinkMaterialResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.OKToTestLinkMaterialResponseBody Body;
        
        public OKToTestLinkMaterialResponse()
        {
        }
        
        public OKToTestLinkMaterialResponse(wsTis.OKToTestLinkMaterialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class OKToTestLinkMaterialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OKToTestLinkMaterialResult;
        
        public OKToTestLinkMaterialResponseBody()
        {
        }
        
        public OKToTestLinkMaterialResponseBody(string OKToTestLinkMaterialResult)
        {
            this.OKToTestLinkMaterialResult = OKToTestLinkMaterialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPanelSerializeResultRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPanelSerializeResult", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetPanelSerializeResultRequestBody Body;
        
        public GetPanelSerializeResultRequest()
        {
        }
        
        public GetPanelSerializeResultRequest(wsTis.GetPanelSerializeResultRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetPanelSerializeResultRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PanelSerialNumber;
        
        public GetPanelSerializeResultRequestBody()
        {
        }
        
        public GetPanelSerializeResultRequestBody(string CustomerName, string Division, string PanelSerialNumber)
        {
            this.CustomerName = CustomerName;
            this.Division = Division;
            this.PanelSerialNumber = PanelSerialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPanelSerializeResultResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPanelSerializeResultResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetPanelSerializeResultResponseBody Body;
        
        public GetPanelSerializeResultResponse()
        {
        }
        
        public GetPanelSerializeResultResponse(wsTis.GetPanelSerializeResultResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetPanelSerializeResultResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPanelSerializeResultResult;
        
        public GetPanelSerializeResultResponseBody()
        {
        }
        
        public GetPanelSerializeResultResponseBody(string GetPanelSerializeResultResult)
        {
            this.GetPanelSerializeResultResult = GetPanelSerializeResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LookupCustAssyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LookupCustAssy", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.LookupCustAssyRequestBody Body;
        
        public LookupCustAssyRequest()
        {
        }
        
        public LookupCustAssyRequest(wsTis.LookupCustAssyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class LookupCustAssyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SerialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Division;
        
        public LookupCustAssyRequestBody()
        {
        }
        
        public LookupCustAssyRequestBody(string SerialNumber, string CustomerName, string Division)
        {
            this.SerialNumber = SerialNumber;
            this.CustomerName = CustomerName;
            this.Division = Division;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LookupCustAssyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LookupCustAssyResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.LookupCustAssyResponseBody Body;
        
        public LookupCustAssyResponse()
        {
        }
        
        public LookupCustAssyResponse(wsTis.LookupCustAssyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class LookupCustAssyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LookupCustAssyResult;
        
        public LookupCustAssyResponseBody()
        {
        }
        
        public LookupCustAssyResponseBody(string LookupCustAssyResult)
        {
            this.LookupCustAssyResult = LookupCustAssyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentRouteStepRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentRouteStep", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetCurrentRouteStepRequestBody Body;
        
        public GetCurrentRouteStepRequest()
        {
        }
        
        public GetCurrentRouteStepRequest(wsTis.GetCurrentRouteStepRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetCurrentRouteStepRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SerialNumber;
        
        public GetCurrentRouteStepRequestBody()
        {
        }
        
        public GetCurrentRouteStepRequestBody(string SerialNumber)
        {
            this.SerialNumber = SerialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentRouteStepResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentRouteStepResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetCurrentRouteStepResponseBody Body;
        
        public GetCurrentRouteStepResponse()
        {
        }
        
        public GetCurrentRouteStepResponse(wsTis.GetCurrentRouteStepResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetCurrentRouteStepResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentRouteStepResult;
        
        public GetCurrentRouteStepResponseBody()
        {
        }
        
        public GetCurrentRouteStepResponseBody(string GetCurrentRouteStepResult)
        {
            this.GetCurrentRouteStepResult = GetCurrentRouteStepResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTestDataFormatsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTestDataFormats", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetTestDataFormatsRequestBody Body;
        
        public GetTestDataFormatsRequest()
        {
        }
        
        public GetTestDataFormatsRequest(wsTis.GetTestDataFormatsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTestDataFormatsRequestBody
    {
        
        public GetTestDataFormatsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTestDataFormatsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTestDataFormatsResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetTestDataFormatsResponseBody Body;
        
        public GetTestDataFormatsResponse()
        {
        }
        
        public GetTestDataFormatsResponse(wsTis.GetTestDataFormatsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetTestDataFormatsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTestDataFormatsResult;
        
        public GetTestDataFormatsResponseBody()
        {
        }
        
        public GetTestDataFormatsResponseBody(string GetTestDataFormatsResult)
        {
            this.GetTestDataFormatsResult = GetTestDataFormatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessTestDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessTestData", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.ProcessTestDataRequestBody Body;
        
        public ProcessTestDataRequest()
        {
        }
        
        public ProcessTestDataRequest(wsTis.ProcessTestDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class ProcessTestDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DataFormat;
        
        public ProcessTestDataRequestBody()
        {
        }
        
        public ProcessTestDataRequestBody(string TestData, string DataFormat)
        {
            this.TestData = TestData;
            this.DataFormat = DataFormat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessTestDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessTestDataResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.ProcessTestDataResponseBody Body;
        
        public ProcessTestDataResponse()
        {
        }
        
        public ProcessTestDataResponse(wsTis.ProcessTestDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class ProcessTestDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessTestDataResult;
        
        public ProcessTestDataResponseBody()
        {
        }
        
        public ProcessTestDataResponseBody(string ProcessTestDataResult)
        {
            this.ProcessTestDataResult = ProcessTestDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTestHistoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTestHistory", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetTestHistoryRequestBody Body;
        
        public GetTestHistoryRequest()
        {
        }
        
        public GetTestHistoryRequest(wsTis.GetTestHistoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetTestHistoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SerialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Division;
        
        public GetTestHistoryRequestBody()
        {
        }
        
        public GetTestHistoryRequestBody(string SerialNumber, string CustomerName, string Division)
        {
            this.SerialNumber = SerialNumber;
            this.CustomerName = CustomerName;
            this.Division = Division;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTestHistoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTestHistoryResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetTestHistoryResponseBody Body;
        
        public GetTestHistoryResponse()
        {
        }
        
        public GetTestHistoryResponse(wsTis.GetTestHistoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetTestHistoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTestHistoryResult;
        
        public GetTestHistoryResponseBody()
        {
        }
        
        public GetTestHistoryResponseBody(string GetTestHistoryResult)
        {
            this.GetTestHistoryResult = GetTestHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastTestResultRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastTestResult", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetLastTestResultRequestBody Body;
        
        public GetLastTestResultRequest()
        {
        }
        
        public GetLastTestResultRequest(wsTis.GetLastTestResultRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetLastTestResultRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SerialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProcessStep;
        
        public GetLastTestResultRequestBody()
        {
        }
        
        public GetLastTestResultRequestBody(string SerialNumber, string CustomerName, string Division, string ProcessStep)
        {
            this.SerialNumber = SerialNumber;
            this.CustomerName = CustomerName;
            this.Division = Division;
            this.ProcessStep = ProcessStep;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastTestResultResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastTestResultResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetLastTestResultResponseBody Body;
        
        public GetLastTestResultResponse()
        {
        }
        
        public GetLastTestResultResponse(wsTis.GetLastTestResultResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetLastTestResultResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLastTestResultResult;
        
        public GetLastTestResultResponseBody()
        {
        }
        
        public GetLastTestResultResponseBody(string GetLastTestResultResult)
        {
            this.GetLastTestResultResult = GetLastTestResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersion", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetVersionRequestBody Body;
        
        public GetVersionRequest()
        {
        }
        
        public GetVersionRequest(wsTis.GetVersionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetVersionRequestBody
    {
        
        public GetVersionRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetVersionResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.GetVersionResponseBody Body;
        
        public GetVersionResponse()
        {
        }
        
        public GetVersionResponse(wsTis.GetVersionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class GetVersionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetVersionResult;
        
        public GetVersionResponseBody()
        {
        }
        
        public GetVersionResponseBody(string GetVersionResult)
        {
            this.GetVersionResult = GetVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OkToTest_BreakoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OkToTest_Breakout", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.OkToTest_BreakoutRequestBody Body;
        
        public OkToTest_BreakoutRequest()
        {
        }
        
        public OkToTest_BreakoutRequest(wsTis.OkToTest_BreakoutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class OkToTest_BreakoutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Division;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SerialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AssemblyNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TesterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ProcessStep;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BreakOutFullPanel;
        
        public OkToTest_BreakoutRequestBody()
        {
        }
        
        public OkToTest_BreakoutRequestBody(string CustomerName, string Division, string SerialNumber, string AssemblyNumber, string TesterName, string ProcessStep, string BreakOutFullPanel)
        {
            this.CustomerName = CustomerName;
            this.Division = Division;
            this.SerialNumber = SerialNumber;
            this.AssemblyNumber = AssemblyNumber;
            this.TesterName = TesterName;
            this.ProcessStep = ProcessStep;
            this.BreakOutFullPanel = BreakOutFullPanel;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OkToTest_BreakoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OkToTest_BreakoutResponse", Namespace="http://jabil.com/GMS/MES_TIS", Order=0)]
        public wsTis.OkToTest_BreakoutResponseBody Body;
        
        public OkToTest_BreakoutResponse()
        {
        }
        
        public OkToTest_BreakoutResponse(wsTis.OkToTest_BreakoutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jabil.com/GMS/MES_TIS")]
    public partial class OkToTest_BreakoutResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OkToTest_BreakoutResult;
        
        public OkToTest_BreakoutResponseBody()
        {
        }
        
        public OkToTest_BreakoutResponseBody(string OkToTest_BreakoutResult)
        {
            this.OkToTest_BreakoutResult = OkToTest_BreakoutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface MES_TISSoapChannel : wsTis.MES_TISSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MES_TISSoapClient : System.ServiceModel.ClientBase<wsTis.MES_TISSoap>, wsTis.MES_TISSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MES_TISSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MES_TISSoapClient.GetBindingForEndpoint(endpointConfiguration), MES_TISSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MES_TISSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MES_TISSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MES_TISSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MES_TISSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MES_TISSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.OKToTestResponse wsTis.MES_TISSoap.OKToTest(wsTis.OKToTestRequest request)
        {
            return base.Channel.OKToTest(request);
        }
        
        public string OKToTest(string CustomerName, string Division, string SerialNumber, string AssemblyNumber, string TesterName, string ProcessStep)
        {
            wsTis.OKToTestRequest inValue = new wsTis.OKToTestRequest();
            inValue.Body = new wsTis.OKToTestRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.AssemblyNumber = AssemblyNumber;
            inValue.Body.TesterName = TesterName;
            inValue.Body.ProcessStep = ProcessStep;
            wsTis.OKToTestResponse retVal = ((wsTis.MES_TISSoap)(this)).OKToTest(inValue);
            return retVal.Body.OKToTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.OKToTestResponse> wsTis.MES_TISSoap.OKToTestAsync(wsTis.OKToTestRequest request)
        {
            return base.Channel.OKToTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.OKToTestResponse> OKToTestAsync(string CustomerName, string Division, string SerialNumber, string AssemblyNumber, string TesterName, string ProcessStep)
        {
            wsTis.OKToTestRequest inValue = new wsTis.OKToTestRequest();
            inValue.Body = new wsTis.OKToTestRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.AssemblyNumber = AssemblyNumber;
            inValue.Body.TesterName = TesterName;
            inValue.Body.ProcessStep = ProcessStep;
            return ((wsTis.MES_TISSoap)(this)).OKToTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.OKToTestLinkMaterialResponse wsTis.MES_TISSoap.OKToTestLinkMaterial(wsTis.OKToTestLinkMaterialRequest request)
        {
            return base.Channel.OKToTestLinkMaterial(request);
        }
        
        public string OKToTestLinkMaterial(string CustomerName, string Division, string LinkMaterialSerialNumber, string AssemblyNumber, string TesterName, string ProcessStep)
        {
            wsTis.OKToTestLinkMaterialRequest inValue = new wsTis.OKToTestLinkMaterialRequest();
            inValue.Body = new wsTis.OKToTestLinkMaterialRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.LinkMaterialSerialNumber = LinkMaterialSerialNumber;
            inValue.Body.AssemblyNumber = AssemblyNumber;
            inValue.Body.TesterName = TesterName;
            inValue.Body.ProcessStep = ProcessStep;
            wsTis.OKToTestLinkMaterialResponse retVal = ((wsTis.MES_TISSoap)(this)).OKToTestLinkMaterial(inValue);
            return retVal.Body.OKToTestLinkMaterialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.OKToTestLinkMaterialResponse> wsTis.MES_TISSoap.OKToTestLinkMaterialAsync(wsTis.OKToTestLinkMaterialRequest request)
        {
            return base.Channel.OKToTestLinkMaterialAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.OKToTestLinkMaterialResponse> OKToTestLinkMaterialAsync(string CustomerName, string Division, string LinkMaterialSerialNumber, string AssemblyNumber, string TesterName, string ProcessStep)
        {
            wsTis.OKToTestLinkMaterialRequest inValue = new wsTis.OKToTestLinkMaterialRequest();
            inValue.Body = new wsTis.OKToTestLinkMaterialRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.LinkMaterialSerialNumber = LinkMaterialSerialNumber;
            inValue.Body.AssemblyNumber = AssemblyNumber;
            inValue.Body.TesterName = TesterName;
            inValue.Body.ProcessStep = ProcessStep;
            return ((wsTis.MES_TISSoap)(this)).OKToTestLinkMaterialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.GetPanelSerializeResultResponse wsTis.MES_TISSoap.GetPanelSerializeResult(wsTis.GetPanelSerializeResultRequest request)
        {
            return base.Channel.GetPanelSerializeResult(request);
        }
        
        public string GetPanelSerializeResult(string CustomerName, string Division, string PanelSerialNumber)
        {
            wsTis.GetPanelSerializeResultRequest inValue = new wsTis.GetPanelSerializeResultRequest();
            inValue.Body = new wsTis.GetPanelSerializeResultRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.PanelSerialNumber = PanelSerialNumber;
            wsTis.GetPanelSerializeResultResponse retVal = ((wsTis.MES_TISSoap)(this)).GetPanelSerializeResult(inValue);
            return retVal.Body.GetPanelSerializeResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.GetPanelSerializeResultResponse> wsTis.MES_TISSoap.GetPanelSerializeResultAsync(wsTis.GetPanelSerializeResultRequest request)
        {
            return base.Channel.GetPanelSerializeResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.GetPanelSerializeResultResponse> GetPanelSerializeResultAsync(string CustomerName, string Division, string PanelSerialNumber)
        {
            wsTis.GetPanelSerializeResultRequest inValue = new wsTis.GetPanelSerializeResultRequest();
            inValue.Body = new wsTis.GetPanelSerializeResultRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.PanelSerialNumber = PanelSerialNumber;
            return ((wsTis.MES_TISSoap)(this)).GetPanelSerializeResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.LookupCustAssyResponse wsTis.MES_TISSoap.LookupCustAssy(wsTis.LookupCustAssyRequest request)
        {
            return base.Channel.LookupCustAssy(request);
        }
        
        public string LookupCustAssy(string SerialNumber, string CustomerName, string Division)
        {
            wsTis.LookupCustAssyRequest inValue = new wsTis.LookupCustAssyRequest();
            inValue.Body = new wsTis.LookupCustAssyRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            wsTis.LookupCustAssyResponse retVal = ((wsTis.MES_TISSoap)(this)).LookupCustAssy(inValue);
            return retVal.Body.LookupCustAssyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.LookupCustAssyResponse> wsTis.MES_TISSoap.LookupCustAssyAsync(wsTis.LookupCustAssyRequest request)
        {
            return base.Channel.LookupCustAssyAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.LookupCustAssyResponse> LookupCustAssyAsync(string SerialNumber, string CustomerName, string Division)
        {
            wsTis.LookupCustAssyRequest inValue = new wsTis.LookupCustAssyRequest();
            inValue.Body = new wsTis.LookupCustAssyRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            return ((wsTis.MES_TISSoap)(this)).LookupCustAssyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.GetCurrentRouteStepResponse wsTis.MES_TISSoap.GetCurrentRouteStep(wsTis.GetCurrentRouteStepRequest request)
        {
            return base.Channel.GetCurrentRouteStep(request);
        }
        
        public string GetCurrentRouteStep(string SerialNumber)
        {
            wsTis.GetCurrentRouteStepRequest inValue = new wsTis.GetCurrentRouteStepRequest();
            inValue.Body = new wsTis.GetCurrentRouteStepRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            wsTis.GetCurrentRouteStepResponse retVal = ((wsTis.MES_TISSoap)(this)).GetCurrentRouteStep(inValue);
            return retVal.Body.GetCurrentRouteStepResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.GetCurrentRouteStepResponse> wsTis.MES_TISSoap.GetCurrentRouteStepAsync(wsTis.GetCurrentRouteStepRequest request)
        {
            return base.Channel.GetCurrentRouteStepAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.GetCurrentRouteStepResponse> GetCurrentRouteStepAsync(string SerialNumber)
        {
            wsTis.GetCurrentRouteStepRequest inValue = new wsTis.GetCurrentRouteStepRequest();
            inValue.Body = new wsTis.GetCurrentRouteStepRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            return ((wsTis.MES_TISSoap)(this)).GetCurrentRouteStepAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.GetTestDataFormatsResponse wsTis.MES_TISSoap.GetTestDataFormats(wsTis.GetTestDataFormatsRequest request)
        {
            return base.Channel.GetTestDataFormats(request);
        }
        
        public string GetTestDataFormats()
        {
            wsTis.GetTestDataFormatsRequest inValue = new wsTis.GetTestDataFormatsRequest();
            inValue.Body = new wsTis.GetTestDataFormatsRequestBody();
            wsTis.GetTestDataFormatsResponse retVal = ((wsTis.MES_TISSoap)(this)).GetTestDataFormats(inValue);
            return retVal.Body.GetTestDataFormatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.GetTestDataFormatsResponse> wsTis.MES_TISSoap.GetTestDataFormatsAsync(wsTis.GetTestDataFormatsRequest request)
        {
            return base.Channel.GetTestDataFormatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.GetTestDataFormatsResponse> GetTestDataFormatsAsync()
        {
            wsTis.GetTestDataFormatsRequest inValue = new wsTis.GetTestDataFormatsRequest();
            inValue.Body = new wsTis.GetTestDataFormatsRequestBody();
            return ((wsTis.MES_TISSoap)(this)).GetTestDataFormatsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.ProcessTestDataResponse wsTis.MES_TISSoap.ProcessTestData(wsTis.ProcessTestDataRequest request)
        {
            return base.Channel.ProcessTestData(request);
        }
        
        public string ProcessTestData(string TestData, string DataFormat)
        {
            wsTis.ProcessTestDataRequest inValue = new wsTis.ProcessTestDataRequest();
            inValue.Body = new wsTis.ProcessTestDataRequestBody();
            inValue.Body.TestData = TestData;
            inValue.Body.DataFormat = DataFormat;
            wsTis.ProcessTestDataResponse retVal = ((wsTis.MES_TISSoap)(this)).ProcessTestData(inValue);
            return retVal.Body.ProcessTestDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.ProcessTestDataResponse> wsTis.MES_TISSoap.ProcessTestDataAsync(wsTis.ProcessTestDataRequest request)
        {
            return base.Channel.ProcessTestDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.ProcessTestDataResponse> ProcessTestDataAsync(string TestData, string DataFormat)
        {
            wsTis.ProcessTestDataRequest inValue = new wsTis.ProcessTestDataRequest();
            inValue.Body = new wsTis.ProcessTestDataRequestBody();
            inValue.Body.TestData = TestData;
            inValue.Body.DataFormat = DataFormat;
            return ((wsTis.MES_TISSoap)(this)).ProcessTestDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.GetTestHistoryResponse wsTis.MES_TISSoap.GetTestHistory(wsTis.GetTestHistoryRequest request)
        {
            return base.Channel.GetTestHistory(request);
        }
        
        public string GetTestHistory(string SerialNumber, string CustomerName, string Division)
        {
            wsTis.GetTestHistoryRequest inValue = new wsTis.GetTestHistoryRequest();
            inValue.Body = new wsTis.GetTestHistoryRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            wsTis.GetTestHistoryResponse retVal = ((wsTis.MES_TISSoap)(this)).GetTestHistory(inValue);
            return retVal.Body.GetTestHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.GetTestHistoryResponse> wsTis.MES_TISSoap.GetTestHistoryAsync(wsTis.GetTestHistoryRequest request)
        {
            return base.Channel.GetTestHistoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.GetTestHistoryResponse> GetTestHistoryAsync(string SerialNumber, string CustomerName, string Division)
        {
            wsTis.GetTestHistoryRequest inValue = new wsTis.GetTestHistoryRequest();
            inValue.Body = new wsTis.GetTestHistoryRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            return ((wsTis.MES_TISSoap)(this)).GetTestHistoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.GetLastTestResultResponse wsTis.MES_TISSoap.GetLastTestResult(wsTis.GetLastTestResultRequest request)
        {
            return base.Channel.GetLastTestResult(request);
        }
        
        public string GetLastTestResult(string SerialNumber, string CustomerName, string Division, string ProcessStep)
        {
            wsTis.GetLastTestResultRequest inValue = new wsTis.GetLastTestResultRequest();
            inValue.Body = new wsTis.GetLastTestResultRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.ProcessStep = ProcessStep;
            wsTis.GetLastTestResultResponse retVal = ((wsTis.MES_TISSoap)(this)).GetLastTestResult(inValue);
            return retVal.Body.GetLastTestResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.GetLastTestResultResponse> wsTis.MES_TISSoap.GetLastTestResultAsync(wsTis.GetLastTestResultRequest request)
        {
            return base.Channel.GetLastTestResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.GetLastTestResultResponse> GetLastTestResultAsync(string SerialNumber, string CustomerName, string Division, string ProcessStep)
        {
            wsTis.GetLastTestResultRequest inValue = new wsTis.GetLastTestResultRequest();
            inValue.Body = new wsTis.GetLastTestResultRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.ProcessStep = ProcessStep;
            return ((wsTis.MES_TISSoap)(this)).GetLastTestResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.GetVersionResponse wsTis.MES_TISSoap.GetVersion(wsTis.GetVersionRequest request)
        {
            return base.Channel.GetVersion(request);
        }
        
        public string GetVersion()
        {
            wsTis.GetVersionRequest inValue = new wsTis.GetVersionRequest();
            inValue.Body = new wsTis.GetVersionRequestBody();
            wsTis.GetVersionResponse retVal = ((wsTis.MES_TISSoap)(this)).GetVersion(inValue);
            return retVal.Body.GetVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.GetVersionResponse> wsTis.MES_TISSoap.GetVersionAsync(wsTis.GetVersionRequest request)
        {
            return base.Channel.GetVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.GetVersionResponse> GetVersionAsync()
        {
            wsTis.GetVersionRequest inValue = new wsTis.GetVersionRequest();
            inValue.Body = new wsTis.GetVersionRequestBody();
            return ((wsTis.MES_TISSoap)(this)).GetVersionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsTis.OkToTest_BreakoutResponse wsTis.MES_TISSoap.OkToTest_Breakout(wsTis.OkToTest_BreakoutRequest request)
        {
            return base.Channel.OkToTest_Breakout(request);
        }
        
        public string OkToTest_Breakout(string CustomerName, string Division, string SerialNumber, string AssemblyNumber, string TesterName, string ProcessStep, string BreakOutFullPanel)
        {
            wsTis.OkToTest_BreakoutRequest inValue = new wsTis.OkToTest_BreakoutRequest();
            inValue.Body = new wsTis.OkToTest_BreakoutRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.AssemblyNumber = AssemblyNumber;
            inValue.Body.TesterName = TesterName;
            inValue.Body.ProcessStep = ProcessStep;
            inValue.Body.BreakOutFullPanel = BreakOutFullPanel;
            wsTis.OkToTest_BreakoutResponse retVal = ((wsTis.MES_TISSoap)(this)).OkToTest_Breakout(inValue);
            return retVal.Body.OkToTest_BreakoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsTis.OkToTest_BreakoutResponse> wsTis.MES_TISSoap.OkToTest_BreakoutAsync(wsTis.OkToTest_BreakoutRequest request)
        {
            return base.Channel.OkToTest_BreakoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsTis.OkToTest_BreakoutResponse> OkToTest_BreakoutAsync(string CustomerName, string Division, string SerialNumber, string AssemblyNumber, string TesterName, string ProcessStep, string BreakOutFullPanel)
        {
            wsTis.OkToTest_BreakoutRequest inValue = new wsTis.OkToTest_BreakoutRequest();
            inValue.Body = new wsTis.OkToTest_BreakoutRequestBody();
            inValue.Body.CustomerName = CustomerName;
            inValue.Body.Division = Division;
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.AssemblyNumber = AssemblyNumber;
            inValue.Body.TesterName = TesterName;
            inValue.Body.ProcessStep = ProcessStep;
            inValue.Body.BreakOutFullPanel = BreakOutFullPanel;
            return ((wsTis.MES_TISSoap)(this)).OkToTest_BreakoutAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MES_TISSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.MES_TISSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MES_TISSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://plkwim0cmp12/MES-TIS/TIS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.MES_TISSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://plkwim0cmp12/MES-TIS/TIS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            MES_TISSoap,
            
            MES_TISSoap12,
        }
    }
}
